# Generated by Django 2.2 on 2019-04-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dare',
            new_name='pub_date',
        ),
    ]
